export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const SET_PUBLIC_CLIENT = 'SET_PUBLIC_CLIENT';
